hrms/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login, logout

admin.autodiscover()

urlpatterns = patterns(  # Examples:
                         # url(r'^hrms/', include('hrms.foo.urls')),
                         # Uncomment the admin/doc line below to enable admin documentation:
                         # Uncomment the next line to enable the admin:
    '',
    url(r'^$', 'ot.views.index', name='idx'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ot/', include('ot.urls')),
    url(r'^accounts/login/$', login, {'template_name': 'ot/login.html'
        }),
    url(r'^accounts/logout/$', 'ot.views.page_logout',  name='logout'),
    )

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

hrms/ot/models.py
#!/usr/bin/env python
# coding: utf-8
from django.contrib.auth.models import User
from django.db import models


OLIVER_STATE_CHOICES = ((u'NEW', u'create'),
                 (u'APPLY', u'apply'),
                 (u'DENY', u'deny'),
                 (u'CONFIRM', u'confirm'),
                 (u'VERIFY', u'verify'),
                 (u'FINISH', u'finish'),
                 )

IVEN_STATE_CHOICES = ((u'0', u'unverify'),
                 (u'1', u'verify'),
                 )


class Oliver(models.Model):
    '''加班申请单
    '''
    applyer = models.ForeignKey(User)
    begintime = models.DateTimeField()
    delta = models.FloatField()
    memo = models.CharField(max_length=255)
    status = models.CharField(max_length=8, choices=OLIVER_STATE_CHOICES, default='NEW')

    def toApply(self):
        self.status = 'APPLY'
        self.save()
        
    def deny(self):
        self.status = 'DENY'
        self.save()
    
    def verifyAll(self):
        pass;
    
    def auditAll(self):
        pass;
    
    def predictTime(self):
        return len(Iven.objects.filter(oliver=self))*self.delta
    
    def actualTime(self):
        return sum([x.actual for x in Iven.objects.filter(oliver=self)])
    
    def __unicode__(self):
        return str(self.id) + ":" + self.applyer.username
            
    

class Iven(models.Model):
    '''个人加班单
    '''
    oliver = models.ForeignKey(Oliver)
    employeer = models.ForeignKey(User)
    beginTime = models.DateTimeField()
    delta = models.FloatField()
    status = models.CharField(max_length=8, choices=IVEN_STATE_CHOICES, default='0')
    actual = models.FloatField(blank=True)
    
    def verify(self):
        self.status = 1
        self.save()
        return self.__checkLast()
    
    def __checkLast(self):
        return len(Iven.objects.filter(oliver=self.oliver, status = 0)) == 0
    
    def audit(self, actualTime):
        self.actual = actualTime
        self.save()


class Simon(models.Model):
    oliver = models.ForeignKey(Oliver)
    operator = models.ForeignKey(User)
    memo = models.CharField(max_length=255)
    action = models.CharField(max_length=8)
    processTime = models.DateTimeField()
    
    
class Overtime(models.Model):
    '''加班申请单
    '''
    STATE_CHOICES = ((u'NEW', u'create'),
                     (u'APPLY', u'apply'),
                     (u'AU', u'audit'),
                     (u'CF', u'confirm'),
                     (u'CAN', u'cancel'),
                     (u'DC', u'decline'),
                     )
    begintime = models.DateTimeField()
    endtime = models.DateTimeField()
    reason = models.CharField(max_length=255)
    remark = models.CharField(max_length=255)
    status = models.CharField(max_length=5, choices=STATE_CHOICES)
    apper = models.ForeignKey(User)

    def __unicode__(self):
        return self.apper.username + ', ' + self.reason

    @property
    def total_time(self):
        initTime = self.begintime.replace(hour=19, minute=0, second=0)
        begin = max(initTime, self.begintime)
        return max(0, int((self.endtime - begin).total_seconds() / 3600))


class OvertimeRef(models.Model):
    '''员工加班中间表
    '''
    employee = models.ForeignKey(User)
    overtimeform = models.ForeignKey(Overtime)

    def __unicode__(self):
        return self.employee + self.overtimeform


class ApplyTrack(models.Model):
    '''审批流程
    '''
    overtimeform = models.ForeignKey(Overtime)
    approval = models.ForeignKey(User)
    approval_note = models.CharField(max_length=255)
    apply_date = models.DateTimeField()
    apply_type = models.CharField(max_length=10)

    def __unicode__(self):
        return self.approval + self.overtimeform + self.type


class userpermission(models.Model):
    class Meta:
        permissions = (
            ("depart_confirm_overtimeform", "Depart director confirm overtimeform"),
            ("hr_audit_overtimeform", "Hr audit overtimeform"),
        )

hrms/templates/apply.html
{% extends "base.html" %}
{% load ot_extra %}
{% block content %}
<div>
	<fieldset>
		<legend>
			加班申请单
		</legend>
		<ul class="form">
			<li>
				<label>开始时间：</label>
				{{ overtimeform.begintime|date:'Y年m月d日 H:i' }}
			</li>
			<li>
				<label>结束时间：</label>
				{{ overtimeform.endtime|date:'Y年m月d日 H:i' }}
			</li>
			<li>
				<label>加班原因：</label>
				{{ overtimeform.reason }}
			</li>
			<li>
				<label>加班人员：</label>
				{% for employee in employees %}
				{{ employee.username }}
				{% endfor %}
			</li>
			<li>
				<label>备注：</label>
				{{ form.remark }}
			</li>
			<li>
				<label>状态：</label>
				{{ overtimeform.status|screenname }}
			</li>
			<li>
				<label>申请人：</label>
				{{ overtimeform.apper.username }}
			</li>
		</ul>
	</fieldset>

	<form action="" method="post">
		{% csrf_token %}
		<fieldset>
			<legend>
				审批单
			</legend>
			<ul class="form">
				<li>
					<label>同意审批：</label>
					{{ applyform.status }}
				</li>
				<li>
					<label>审批意见：</label>
					{{ applyform.approval_note }}
				</li>
				<li>
					<input type="submit" class="submit" value="提交" />
				</li>
			</ul>
		</fieldset>
	</form>
</div>
{% endblock %}

hrms/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Jinjiang Overtime Management System</title>
    <!-- Framework CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/blueprint/screen.css" type="text/css"
          media="screen, projection">
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/blueprint/print.css" type="text/css" media="print">
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/RMSforms-v0.5.css" type="text/css" media="screen">
    <link rel="stylesheet" href="{{ STATIC_URL }}SexyButtons/sexybuttons.css" type="text/css" media="screen">
    <!--[if lt IE 8]><link rel="stylesheet" href="{{ STATIC_URL }}styles/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->

    <!-- Import fancy-type plugin for the sample page. -->
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/blueprint/plugins/fancy-type/screen.css" type="text/css"
          media="screen, projection">
    <link type="text/css" href="{{ STATIC_URL }}jquery/css/ui-lightness/jquery-ui-1.8.23.custom.css" rel="stylesheet" />
    <script type="text/javascript" src="{{ STATIC_URL }}jquery/js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery/js/jquery-ui-1.8.23.custom.min.js"></script>

    <script type="text/javascript" src="{{ STATIC_URL }}My97DatePicker/WdatePicker.js"></script>

</head>

<body>
<div class="container">
{% if request.user.is_authenticated %}
欢迎你，{{ request.user.username }}。<a href="{% url ot_resetPwd %}">修改密码</a> <a href="{% url logout %}">退出</a>
{% endif %}
    <h1 align="center">锦江电商加班管理系统</h1>
    <hr>
    <div class="span-3 colborder" style="font-size: 14px;">
        <ul>
            <li><a href="{% url idx %}">加班列表</a></li><br>
            {% if perms.ot.add_overtime %}
                <li><a href="{% url ot_new %}">申请加班</a></li><br>
            {% endif %}
            <li><a href="{% url ot_applyFormList %}">部门确认</a></li><br>
            {% if perms.ot.hr_audit_overtimeform %}
                <li><a href="{% url ot_auditFormList %}">人事审批</a></li><br>
            {% endif %}
            <li>加班查询</li><br>
            <li><a href="{% url ot_stat %}">加班统计</a></li><br>
        </ul>

    </div>
    <div class="span-20 last">
        {% block content %}
        {% endblock %}
	<p>
	    <a href="http://djangoproject.com/">Django</a><br/>
	</p>
    </div>
</div>

</body>

</html>

hrms/templates/detail.html
{% extends "base.html" %}
{% load ot_extra %}
{% block content %}
<div>
	<fieldset>
		<legend>
			加班申请单
		</legend>
		<ul class="form">
			<li>
				<label>开始时间：</label>
				{{ overtimeform.begintime|date:'Y年m月d日 H:i' }}
			</li>
			<li>
				<label>结束时间：</label>
				{{ overtimeform.endtime|date:'Y年m月d日 H:i' }}
			</li>
			<li>
				<label>加班原因：</label>
				{{ overtimeform.reason }}
			</li>
			<li>
				<label>加班人员：</label>
				{% for employee in employees %}
				{{ employee.username }}
				{% endfor %}
			</li>
			<li>
				<label>备注：</label>
				{{ overtimeform.remark }}
			</li>
			<li>
				<label>状态：</label>
				{{ overtimeform.status|screenname }}
			</li>
			<li>
				<label>申请人：</label>
				{{ overtimeform.apper.username }}
			</li>
		</ul>
	</fieldset>

</div>
{% endblock %}

hrms/templates/index.html
{% extends "base.html" %}
{% load ot_extra %}
{% block content %}

{% load pagination_tags %}
{% autopaginate otList 5 %}
    <div>
            <table  border="0" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th class="span-3">申请人</th>
                        <th class="span-6">加班开始时间</th>
                        <th class="span-6">加班结束时间</th>
                        <th class="span-3">加班单状态</th>
                        <th class="span-3">查看详情</th>
                        <th class="span-3">操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for overtimeform in otList %}
                    <tr>
                        <td>{{ overtimeform.apper.username }}</td>
                        <td>{{ overtimeform.begintime|date:'Y年m月d日 H:i' }}</td>
                        <td>{{ overtimeform.endtime|date:'Y年m月d日 H:i' }}</td>
                        <td>{{ overtimeform.status|screenname }}</td>
                        <td><a href="{% url ot_overtime_detail overtimeform.id %}">详情</a></td>
                        <td>
                            {% if perms.ot.depart_confirm_overtimeform %}
                                {% ifequal overtimeform.status 'NEW' %}
                                    <a href="{% url ot_apply overtimeform.id %}">确认</a>
                                {% endifequal %}
                            {% endif %}
                            {% if perms.ot.hr_audit_overtimeform %}
                                {% ifequal overtimeform.status 'APPLY' %}
                                    <a href="{% url ot_confirm overtimeform.id %}">审核</a>
                                {% endifequal %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
    </div>
{% paginate %}
                
{% endblock %}

hrms/templates/overtimeForm.html
{% extends "base.html" %}

{% block content %}
<div>
	<form action="" method="post">
		{% csrf_token %}
		<input type="hidden" name="status" value="NEW" />
		<input type="hidden" name="apper" value="{{model.id}}" />
		<fieldset>
			<legend>
				加班申请单
			</legend>
			<ul class="form">
				<li>
					<label>开始时间：</label>
					{{ form.begintime }}
				</li>
				<li>
					<label>结束时间：</label>
					{{ form.endtime }}
				</li>
				<li>
					<label>加班原因：</label>
					{{ form.reason }}
				</li>
				<li>
					<label>加班人：</label>
					{% for employee in employees %}
					<input type="checkbox" name="employee" value="{{employee.id}}" style="float:none;">
					{{ employee.username }}
					{% endfor %}
				</li>
				<li>
					<label>备注：</label>
					{{ form.remark }}
				</li>
				<li>
					<input type="submit" class="submit" value="提交"/>
				</li>
			</ul>
		</fieldset>
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#id_begintime,#id_endtime').click(initDatePicker).attr('readonly', 'readonly');
	})
	function initDatePicker() {
		WdatePicker({
			dateFmt : 'yyyy-MM-dd HH:mm'
		});
	}
</script>

{% endblock %}

hrms/templates/resetPassword.html
{% extends "base.html" %}

{% block content %}
<div>
	<form action="" method="post">
		{% csrf_token %}
		<fieldset>
			<legend>
				重置密码
			</legend>
			<ul class="form">
				<li>
					<label>原始密码：</label>
					{{ resetPwdForm.oldPwd }}<label style="color: #ff0000;">{{ error }}</label>
				</li>
				<li>
					<label>新密码：</label>
                    {{ resetPwdForm.newPwd }}{{ resetPwdForm.errors.newPwd }}
				</li>
				<li>
					<label>确认密码：</label>
                    {{ resetPwdForm.confirmPwd }}{{ resetPwdForm.errors.confirmPwd }}
				</li>
				<li>
					<input type="submit" class="submit" value="提交"/>
				</li>
			</ul>
		</fieldset>
	</form>
</div>
{% endblock %}